# Generated by Django 5.2.17 on 2026-08-14 01:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTelemetria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispositivo_id', models.CharField(max_length=100)),
                ('tipo_dispositivo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='telemetria_files/%Y/%m/%d/')),
                ('tamano_bytes', models.BigIntegerField()),
                ('timestamp_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.CharField(help_text='ID o Hostname del contenedor/sensor', max_length=100)),
                ('tipo_dispositivo', models.CharField(help_text='Ej: cardiograma, respirador', max_length=50)),
                ('datos_payload', models.JSONField(help_text='Lectura biométrica en formato JSON')),
                ('timestamp_cliente', models.FloatField(blank=True, help_text='Timestamp Unix T1 enviado por el cliente', null=True)),
                ('timestamp_recepcion', models.DateTimeField(auto_now_add=True, help_text='Timestamp T2 registrado en Django')),
            ],
        ),
    ]
