# Generated by Django 5.2.17 on 2026-08-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivotelemetria',
            options={'ordering': ['-timestamp_subida']},
        ),
        migrations.AlterModelOptions(
            name='lecturadispositivo',
            options={'ordering': ['-timestamp_recepcion']},
        ),
        migrations.AlterField(
            model_name='archivotelemetria',
            name='dispositivo_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturadispositivo',
            name='datos_payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='lecturadispositivo',
            name='dispositivo_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturadispositivo',
            name='timestamp_cliente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturadispositivo',
            name='timestamp_recepcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lecturadispositivo',
            name='tipo_dispositivo',
            field=models.CharField(max_length=50),
        ),
    ]
