services:
  edge_django:
    build:
      context: ./edge-node
      dockerfile: Dockerfile
    container_name: edge_django
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./edge-node:/app
    environment:
      - DB_HOST=nodo_edge_postgres
      - DB_PORT=5432
      - DB_NAME=hospital_db
      - DB_USER=admin
      - DB_PASS=admin
      - REDIS_HOST=nodo_edge_redis
      - REDIS_PORT=6379
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - red_hospitalaria_privada
    depends_on:
      - db
      - redis
    labels:
      proyecto: "hospital_5g"
      componente: "nodo_edge"

  db:
    image: postgres:16-alpine
    container_name: nodo_edge_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hospital_db
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      - red_hospitalaria_privada
    labels:
        proyecto: "hospital_5g"
        componente: "infraestructura"

  redis:
    image: redis:7-alpine
    container_name: nodo_edge_redis
    networks:
      - red_hospitalaria_privada
    labels:
        proyecto: "hospital_5g"
        componente: "infraestructura"

  ##################
 ## DISPOSITIVOS ##
##################
  dispositivo_cardiograma:
    image: alpine:latest
    container_name: dispositivo_cardiograma_1
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
    - red_hospitalaria_privada
    labels:
        proyecto: "hospital_5g"
        tipo: "dispositivo_medico"
        especialidad: "cardiologia"

  dispositivo_respirador:
    image: alpine:latest
    container_name: dispositivo_respirador_1
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - red_hospitalaria_privada
    labels:
        proyecto: "hospital_5g"
        tipo: "dispositivo_medico"
        especialidad: "urgencias"

volumes:
    postgres_data:

networks:
  red_hospitalaria_privada:
    driver: bridge
